
def grap_open():
    set_digital_output(2, OFF)
    set_digital_output(1, ON)
    wait(1.0)
def grap_close():
    set_digital_output(2, ON)
    set_digital_output(1, OFF)
    wait(1.0)
	
	
def forward():   
    movel(System_first_up, 60, 100)
    grap_open()
    movel(System_first_down, 50, 100)
    grap_close()
    wait_digital_input(2, ON)
    movel(System_first_up, 60, 100)

    movel(System_second_up, 60, 100)

    a = get_current_posx()[0]

    count = 0

    task_compliance_ctrl([3000, 3000, 100, 200, 200, 200])
    fd = [0, 0, -15, 0, 0,  0]
    fctrl_dir = [0, 0, 1, 0, 0, 0]
    set_desired_force(fd, dir=fctrl_dir, mod=DR_FC_MOD_REL)

    while count < 10:
        force_ext = get_tool_force(DR_BASE)
        b = get_current_posx()[0]
        if force_ext[2] >= 13:
            b[5] += 3.0
            #tp_popup("{}".format(b))
            movel(b, 10, 100)
            count += 1
		
        if b[2] <= System_second_down[2] + 10:
            release_force()
            wait(0.5)
            release_compliance_ctrl()
            set_digital_output(2, OFF)
            set_digital_output(1, ON)
            movel(System_second_up, 50, 100)
            tp_popup("finish")
            break

    movel(System_second_up, 50, 100)
    tp_popup("이물질을 제거하세요")
            
    release_force()
    wait(0.5)
    release_compliance_ctrl()

def backward():
    grap_open()
    movel(System_second_h1_up, 80, 100)
    movel(System_second_h1_down, 80, 100)
    grap_close()
    movel(System_second_h1_up, 80, 100)
    movel(System_first_h1_up, 80, 100)
    
    count = 0
    
    task_compliance_ctrl([3000, 3000, 100, 200, 200, 200])
    fd = [0, 0, -15, 0, 0,  0]
    fctrl_dir = [0, 0, 1, 0, 0, 0]
    set_desired_force(fd, dir=fctrl_dir, mod=DR_FC_MOD_REL)

    while count < 20:
            force_ext = get_tool_force(DR_BASE)
            b = get_current_posx()[0]
            if force_ext[2] >= 13:
                b[5] += 3.0
                #tp_popup("{}".format(b))
                movel(b, 10, 100)
                count += 1
		
            if b[2] <= System_first_h1_down[2] + 10:
                release_force()
                wait(0.5)
                release_compliance_ctrl()
                set_digital_output(2, OFF)
                set_digital_output(1, ON)
                movel(System_first_h1_up, 50, 100)
                # tp_popup("finish")
                break
    
    grap_open()
    movel(System_second_h2_up, 80, 100)
    movel(System_second_h2_down, 80, 100)
    grap_close()
    movel(System_second_h2_up, 80, 100)
    movel(System_first_h2_up, 80, 100)
    
    count = 0

    task_compliance_ctrl([3000, 3000, 100, 200, 200, 200])
    fd = [0, 0, -10, 0, 0,  0]
    fctrl_dir = [0, 0, 1, 0, 0, 0]
    set_desired_force(fd, dir=fctrl_dir, mod=DR_FC_MOD_REL)

    while count < 20:
            force_ext = get_tool_force(DR_BASE)
            b = get_current_posx()[0]
            if force_ext[2] >= 7:
                b[5] += 1.0
                #tp_popup("{}".format(b))
                movel(b, 10, 100)
                count += 1
		
            if b[2] <= System_first_h2_down[2] + 10:
                release_force()
                wait(0.5)
                release_compliance_ctrl()
                grap_open()
                movel(System_first_h2_up, 50, 100)
                # tp_popup("finish")
                wait(1)
                break
    grap_open()
    movel(System_second_h3_up, 80, 100)
    movel(System_second_h3_down, 80, 100)
    grap_close()
    movel(System_second_h3_up, 80, 100)
    movel(System_first_h3_up, 80, 100)
    
    count = 0

    task_compliance_ctrl([3000, 3000, 100, 200, 200, 200])
    fd = [0, 0, -10, 0, 0,  0]
    fctrl_dir = [0, 0, 1, 0, 0, 0]
    set_desired_force(fd, dir=fctrl_dir, mod=DR_FC_MOD_REL)

    while count < 20:
            force_ext = get_tool_force(DR_BASE)
            b = get_current_posx()[0]
            if force_ext[2] >= 7:
                b[5] += 1.0
                #tp_popup("{}".format(b))
                movel(b, 10, 100)
                count += 1
		
            if b[2] <= System_first_h3_down[2] + 10:
                release_force()
                wait(0.5)
                release_compliance_ctrl()
                grap_open()
                movel(System_first_h3_up, 50, 100)
                # tp_popup("finish")
                break
        
    
    
a = False


while a != True:
    force_ext2 = get_tool_force(DR_BASE)
    d = abs(force_ext2[0])
    c = abs(force_ext2[1])
	
    if d > c and d > 40:
        forward()
        a = True
    elif c > d and c > 40:
        backward()
        a = True